version: '3'

services:
  mqtt-broker:
    image: mvyas7/mqtt-broker:v1
    container_name: mqtt-broker
    ports:
      - "1884:1883"
    networks:
      - mqtt-net

  grafana:
    image: mvyas7/grafana:v1
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mqtt-net

networks:
  mqtt-net:
    driver: bridge